# Compiler
CXX = g++
# Compiler flags
CXXFLAGS = -Wall -std=c++11

# Output executable name
TARGET = lms

# Source files
SRCS = Account.cpp Book.cpp Librarian.cpp Library_database.cpp LMS.cpp main.cpp Staff.cpp User.cpp

# Object files
OBJS = $(SRCS:.cpp=.o)

# Default target
all: $(TARGET)

# Build target
$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(OBJS)

# Compile .cpp to .o
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $<

# Clean compiled files
clean:
	rm -f $(OBJS) $(TARGET)
